; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.29"

; Modules
projects[a11y_checklist][version] = "1.x-dev"

projects[admin_menu][version] = "3.0-rc4"

projects[ctools][version] = "1.4"

projects[checklistapi][version] = "1.1"

projects[ckeditor][version] = "1.15"

projects[colorbox][version] = "2.7"

projects[date][version] = "2.7"

projects[entity][version] = "1.5"

projects[media][version] = "1.4"

projects[imce][version] = "1.9"

projects[insert][version] = "1.3"

projects[libraries][version] = "2.2"

projects[mediaelement][version] = "1.2"

projects[module_filter][version] = "2.0-alpha2"

projects[pathauto][version] = "1.2"

projects[testswarm][version] = "1.1"

projects[token][version] = "1.5"

projects[views][version] = "3.8"

; Themes
projects[zen][version] = "5.5"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[tests][download][type] = ""
;projects[tests][download][url] = ""
;projects[tests][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[psr_0_test][download][type] = ""
;projects[psr_0_test][download][url] = ""
;projects[psr_0_test][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[sub1][download][type] = ""
;projects[sub1][download][url] = ""
;projects[sub1][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox.git"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[quail][download][type] = "git"
libraries[quail][download][url] = "https://github.com/quailjs/quail.git"
libraries[quail][directory_name] = "quail"
libraries[quail][type] = "library"

